name: Workflow Using Configuration Variables||| Github
run-name: Created by ${{ gitbub.actor}}
on:
  workflow_dispatch:
env:
  Cloud: Azure_Cloud
jobs:
  First_job:
    name: My First Job
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
    - name: My First Step
      run: echo "$Greeting $User is using $Cloud to build ${{ vars.Project_Id }}
      env: 
        User: Sunil
    
