name: Workflow Using Configuration Variables
on:
  workflow_dispatch:
env:
  Cloud: Azure_Cloud
jobs:
  Build:
    name: My First Build Job 
    env:
      Greeting: Hello
    runs-on: ubuntu-latest

    steps:
      - name: "Hello User Good Afternoon"
        run: echo "$Greeting $User is using $Cloud for ${{ vars.PROJECT_ID1 }} Automation"  # using configuration variable by ${{ vars.enc }}
        env:
          User: Sunil
  
