name: Workflow With Variable
on: 
  workflow_dispatch
env: 
  Cloud: Azure-Cloud
jobs:
  Build:
    name: First Build Job
    env:
      Greeting: Hello
    runs-on: ubuntu-latest
    steps:
      - name: Hello Sunil, Today is Monday
        run: echo "$Greeting $User is using $Cloud"
        env:
          User: 'Sunil'
